apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ofagent
  namespace: voltha
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ofagent
      annotations:
        cni: "calico"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: ofagent
        image: volthacore/voltha-ofagent:rich
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
        - "/ofagent/ofagent/main.py"
        - "-v"
        - "--consul=consul.$(NAMESPACE).svc.cluster.local:8500"
        - "--controller=onos:6653"
        - "--grpc-endpoint=rw-core.$(NAMESPACE).svc.cluster.local:50057"
        - "--enable-tls"
        - "--key-file=/ofagent/pki/voltha.key"
        - "--cert-file=/ofagent/pki/voltha.crt"
