# -------------
# Build stage

FROM golang:1.10-alpine3.9

# Install required packages
RUN apk add --no-cache wget git make build-base

# Prepare directory structure
RUN ["mkdir", "-p", "/build"]
RUN ["mkdir", "-p", "$GOPATH/src", "$GOPATH/pkg", "$GOPATH/bin"]
RUN ["mkdir", "-p", "$GOPATH/src/github.com/opencord/voltha-go"]

WORKDIR $GOPATH/src/github.com/opencord/voltha-go

# Copy common files.
COPY common ./common
COPY db ./db
COPY kafka ./kafka
COPY vendor ./vendor
