version: '2'
services:
  rw_core:
    image: voltha-rw-core
    entrypoint:
        - /app/rw_core
        - -kv_store_type=etcd
        - -kv_store_host=${DOCKER_HOST_IP}
        - -kv_store_port=2379
        - -grpc_host=${DOCKER_HOST_IP}
        - -grpc_port=50057
        - -banner=true
        - -kafka_adapter_host=10.176.230.190
        - -kafka_adapter_port=9092
        - -kafka_cluster_host=10.176.230.190
        - -kafka_cluster_port=9092
        - -rw_core_topic=rwcore
        - -log_level=0
    ports:
      - "50057:50057"
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
    networks:
    - default

networks:
  default:
    driver: bridge
